name: Ruff Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v3
        with:
          # version: '0.12.1'  # можно указать конкретную версию Ruff, по умолчанию latest
          # args: check .      # можно указать дополнительные аргументы, по умолчанию "check"
          # src: '.'           # пути для проверки, по умолчанию "." и "src"
